/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WeatherImport } from './routes/weather'
import { Route as IndexImport } from './routes/index'
import { Route as WeatherIndexImport } from './routes/weather/index'
import { Route as WeatherLatLngIndexImport } from './routes/weather/$lat/$lng/index'

// Create/Update Routes

const WeatherRoute = WeatherImport.update({
  path: '/weather',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WeatherIndexRoute = WeatherIndexImport.update({
  path: '/',
  getParentRoute: () => WeatherRoute,
} as any)

const WeatherLatLngIndexRoute = WeatherLatLngIndexImport.update({
  path: '/$lat/$lng/',
  getParentRoute: () => WeatherRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherImport
      parentRoute: typeof rootRoute
    }
    '/weather/': {
      id: '/weather/'
      path: '/'
      fullPath: '/weather/'
      preLoaderRoute: typeof WeatherIndexImport
      parentRoute: typeof WeatherImport
    }
    '/weather/$lat/$lng/': {
      id: '/weather/$lat/$lng/'
      path: '/$lat/$lng'
      fullPath: '/weather/$lat/$lng'
      preLoaderRoute: typeof WeatherLatLngIndexImport
      parentRoute: typeof WeatherImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  WeatherRoute: WeatherRoute.addChildren({
    WeatherIndexRoute,
    WeatherLatLngIndexRoute,
  }),
})

/* prettier-ignore-end */
