/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WeatherIndexImport } from './routes/weather/index'
import { Route as WeatherLatLngIndexImport } from './routes/weather/$lat/$lng/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WeatherIndexRoute = WeatherIndexImport.update({
  path: '/weather/',
  getParentRoute: () => rootRoute,
} as any)

const WeatherLatLngIndexRoute = WeatherLatLngIndexImport.update({
  path: '/weather/$lat/$lng/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/weather/': {
      id: '/weather/'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherIndexImport
      parentRoute: typeof rootRoute
    }
    '/weather/$lat/$lng/': {
      id: '/weather/$lat/$lng/'
      path: '/weather/$lat/$lng'
      fullPath: '/weather/$lat/$lng'
      preLoaderRoute: typeof WeatherLatLngIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  WeatherIndexRoute,
  WeatherLatLngIndexRoute,
})

/* prettier-ignore-end */
